### ISSUE TITLE
Standardize error and message data classes

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/Aind.Behavior.Services#158]

**Comment by bruno-f-cruz** [comment]
Message[T]:
   Process: str
   Host: str
   timestamp : datetime ?
   message_type: str
   payload: T

**Comment by bruno-f-cruz** [comment]
LogPayload:
   level: Literal[Warning, Info, ...]
   message: str


LogMessage = Message[LogPayload]

**Comment by patricklatimer** [comment]
Is "Process" the PID of the message sender? It might be also useful to include application name and version.

Also what's message_type, is it different than the type `T` of the payload?
 
I think at least for the LogPayload, it might be nice to add a dict-like field for context key-value pairs. Alternatively the message could be a json string, but it feels cleaner to expect that logs should look like a short string message accompanied by a context dictionary. Honestly that might be a good thing to include in the generic `Message`, as it's good to have a place to stuff extra information that doesn't fall into a schematized field.

**Comment by bruno-f-cruz** [comment]
> Is "Process" the PID of the message sender? It might be also useful to include application name and version.

Thats a good question. In my mind, process is a simple human-readable "tag" that allows consumers to quickly figure out whether to use the message or not (e.g. if I am waiting for something that I should receive from application Foo, I just need to filter on this tag). This becomes much harder if we derive the Process from a PID has it changes from different process runs.

I am ok making PID part of the log, but it is not that clear to me how useful it would be.
Regarding version, I think we can make it an optional[str] in log (not message) that can be used to enter any sort of version information. I am reluctant on making it SemVer as a valid alternative is to push a commit sha to it instead.

> Also what's message_type, is it different than the type T of the payload?
 
You need a way to afford people to do runtime casting of message types. `message_type` can work as the discriminator tag (https://swagger.io/docs/specification/v3_0/data-models/inheritance-and-polymorphism/#discriminator)

> I think at least for the LogPayload, it might be nice to add a dict-like field for context key-value pairs. Alternatively the message could be a json string, but it feels cleaner to expect that logs should look like a short string message accompanied by a context dictionary. Honestly that might be a good thing to include in the generic Message, as it's good to have a place to stuff extra information that doesn't fall into a schematized field.

Not sure I follow. If we want to "enforce" a log structure, we can model it directly in LogPayload. Is it the case that you want to split the message field in two?
```
LogPayload:
   level: Literal[Warning, Info, ...]
   context: JSONable (can you describe what you except to find here?)
   message: str (anything goes?)
   application_version: Optional[str]

```

**Comment by patricklatimer** [comment]
>> Is "Process" the PID of the message sender? It might be also useful to include application name and version.

>Thats a good question. In my mind, process is a simple human-readable "tag"...

Okay, so that's basically what I meant by "application name", I don't care that much about PID, just wanted to check, as "Process" implied "PID" to me.

-------

>> I think at least for the LogPayload, it might be nice to add a dict-like field for context key-value pairs. Alternatively the message could be a json string, but it feels cleaner to expect that logs should look like a short string message accompanied by a context dictionary. Honestly that might be a good thing to include in the generic Message, as it's good to have a place to stuff extra information that doesn't fall into a schematized field.

> Not sure I follow. If we want to "enforce" a log structure, we can model it directly in LogPayload. Is it the case that you want to split the message field in two?

I think yes, we should split the "message" field in two. In almost every log I've sent from an application (peruse the [logserver](http://eng-logtools:8080/?page_length=500)), I have an event that occurred that I want to communicate, and I also have a bunch of other context I wish to pass along.

For an example of a typical log I'd want to write
```yaml
timestamp: ...
rig_id: WL.1
hostname: W10DT....
application: waterlog
version: 4.0.2
payload:
    level: Info
    message: Mouse has been watered
    context: 
        mouse_id: 614173
        user_id: patrick.latimer
        mouse_state: Water Restricted
        mouse_weight_g: 20
        water_supplement_ml: 1
```
